### PR TITLE
Adding images and the reload patch, rebasing from @daminisatya and @aviaryan

### PR DESCRIPTION
**Pull request by sudheesh001**

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@sudheesh001 This PR has merge conflicts ...

**Comment by sudheesh001** [comment]
@jig08 review ?

@mariobehling @mananwason

**Comment by mariobehling** [comment]
Hi, please always give me a link to a github pages site with the changes. Time is limited and it should be easy for you. Cheers.

**Comment by sudheesh001** [comment]
http://daminisatya.github.io/2016.fossasia.org/#speakers @mariobehling

**Pull request closed without merging**
