### PR TITLE
Updated Speaker Section

### PR DESCRIPTION
**Pull request by shubh1m**
Fixes https://github.com/fossasia/2016.fossasia.org/issues/42

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@iamshubh22 Its always helpful to add a preview link (viz `<username>.github.io/2016.fossasia.org`) for easier check & merge.

**Comment by shubh1m** [comment]
@jig08 Done. Check this out https://iamshubh22.github.io/2016.fossasia.org/
screenshot from 2016-03-11 13-19-53

**Comment by jigyasa-grover** [comment]
@iamshubh22 When hovered over, the bio takes up more width than the image (refer: screenshot attached)

screenshot from 2016-03-11 14 26 22

**Comment by shubh1m** [comment]
@jig08 See if it is fine now https://iamshubh22.github.io/2016.fossasia.org/
screenshot from 2016-03-11 15-21-35

**Comment by jigyasa-grover** [comment]
Yep, better.

**Pull request merged**
