### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by yashk0thari**
#140 Added missing speaker's profiles ...

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/Beta-King.2016.fossasia.org/ --> preview link...

**Comment by anshumanv** [comment]
As already pointed by @mariobehling in #144 which issue is this solving?
You have referenced a PR in your comment and it should instead have an issue link which it is solving, please make appropriate changes.

**Review by yashk0thari — COMMENTED** [review]
#140 Added missing speaker's list...

**Comment by yashk0thari** [comment]
You want me to added the corresponding issue link in my initial PR discription ??

**Comment by yashk0thari** [comment]
making that change...

**Pull request closed without merging**
