### PR TITLE
Added hover property for social icons in the side menu

### PR DESCRIPTION
**Pull request by harsh-jindal**

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@ParthS007 Please review it.

**Review by isuruAb — COMMENTED** [review]
please provide a preview link

**Comment by harsh-jindal** [comment]
@isuruAb https://harsh-jindal.github.io/2016.fossasia/ This is the link

**Review by akshatnitd — CHANGES_REQUESTED** [review]
The changes look good. But do not make the changes in the `font-awesome.min.css`. Instead make the changes in the `custom.css`.

**Comment by harsh-jindal** [comment]
@akshatnitd Closed this pull request due to some problems.Made a new pull request.

**Pull request closed without merging**
