### PR TITLE
Update index.html (Added missing speaker's list 8+)

### PR DESCRIPTION
**Pull request by yashk0thari**
#138 I've added missing speaker's list (8)

### CODE REVIEW

**Comment by yashk0thari** [comment]
Is it ohk now ??

**Comment by yashk0thari** [comment]
if not, could you please describe what changes i have to do... sorry for the inconvenience...

**Comment by anshumanv** [comment]
The `#140` that you wrote in the PR description should actually be an issue number corresponding to this PR.

**Comment by yashk0thari** [comment]
ohkk, sorry for that. i thought that was the issue number only, i've made the change. looks good ??

**Review by anshumanv — APPROVED** [review]

**Comment by yashk0thari** [comment]
How much longer ?? is there anything left to do ??

**Review by akshatnitd — APPROVED** [review]
LGTM :)

**Comment by akshatnitd** [comment]
@Beta-King Make sure you complete the PR template and submit it, instead of deleting it.

Provide a deployment link, so that we can test it and then merge

**Comment by yashk0thari** [comment]
kk, guys i've submitted a task in GCI for review and the pull request has been merged, but hasnt been approved in the GCI task menu; could you plz do that, it this one >> Website: FOSSASIA Summit 2017: Add missing Profile Links of Speakers and Team ( FOSSASIA )

Thanks :D

**Comment by yashk0thari** [comment]
and gitter is not working, so this is only way i could communicate

**Comment by yashk0thari** [comment]
Could you approve the task??

**Comment by yashk0thari** [comment]
https://beta-king.github.io/Beta-King.2016.fossasia.org/ --> preview link :D

**Comment by akshatnitd** [comment]
@Beta-King Please squash the commits

**Comment by yashk0thari** [comment]
ohk

**Comment by yashk0thari** [comment]
im having problems merging... im opening another PR

**Pull request closed without merging**
