### PR TITLE
social Links Added

### PR DESCRIPTION
**Pull request by SilentFlame**
#72  resolved.

@championswimmer @mariobehling 
do we need more social links to add.

removed underlines from headings too. 
will add facebook and youtube link in a while.

### CODE REVIEW

**Comment by SilentFlame** [comment]
preview for the same. 
[preview](http://silentflame.github.io/2016.fossasia.org/schedule/)

**Comment by jig08** [comment]
@SilentFlame Add Facebook too as mentioned in Issue #72

**Comment by rctay** [comment]
Your commit also includes the unrelated change of 'trailing whitespace removal'. It would be best if it didn't do so.

**Comment by jigyasa-grover** [comment]
@SilentFlame This PR deals with Issue #72.

In #75 you need to add each speakers info and social media icons with link to Website/Blog, GitHub, Twitter, LinkedIn when expanded.

**Comment by SilentFlame** [comment]
@jig08 oh sorry I misunderstood the social links.

editing the PR description.

**Comment by rctay** [comment]
@SilentFlame just do the social links for one entry in the schedule. We will figure out how to programmatically duplicate it for each of the other entries in the schedule.

**Comment by SilentFlame** [comment]
@rctay currently I resolved #72.
now let me work on the speakers social links extraction.

**Comment by joerx** [comment]
1. index.html is generated by the script in this repo: https://github.com/fossasia/open-event-scraper. Do not edit it directly.
2. Icons are ugly. Please see #72 for active discussion
3. Schedule page is using [Bootstrap](getbootstrap.com) which has built-in support for right aligned content, no need for custom floats (which will likely break in mobile layouts)
4. Why did you remove the underline for session titles? 

If you ever want your PRs accepted: please try to understand and respect other peoples code, catch up on recent frontend tools & techniques and follow up on active discussions

**Comment by SilentFlame** [comment]
sorry for that.
I'll keep that in mind from next times.
for the removing of the underlines I guess it's preetier that way, but will take others consents too from next times.

**Pull request closed without merging**
