### PR TITLE
Disabled new tab for schedule link

### PR DESCRIPTION
**Pull request by yask123**

### CODE REVIEW

**Comment by mariobehling** [comment]
What is the issue with the new tab? The idea is, that everyone has the schedule in a new tab. Why not?

**Comment by mananwason** [comment]
@mariobehling There are 2 bugs here. If you click on speakers, a new tab is opened and if you click on schedule, there also a new tab is opened. For speakers, it shouldn't open in a new tab altogether. For schedule, personally I would prefer opening in the same tab because the control will be with the user as he can anyways open it in a new tab via options in the browser. So, I think we should merge this.

**Comment by mariobehling** [comment]
@mananwason actually if you click on speakers in the main menu, it scrolls down and does not open in a new tab. anyways, i am merging this.

**Comment by mananwason** [comment]
@mariobehling I thought this was the case but it seems like it works fine in other browsers, just not with Chrome Version 48.0.2564.116 (64-bit).

**Pull request merged**
