### PR TITLE
Added speakers images, implemented speaker's bio

### PR DESCRIPTION
**Pull request by aviaryan**
See https://github.com/fossasia/2016.fossasia.org/issues/19#issuecomment-192327145 for more information.

### CODE REVIEW

**Comment by aviaryan** [comment]
This PR includes #22

**Comment by jigyasa-grover** [comment]
- Close PR #22 @aviaryan , then ?
- Squash commits pls ?

**Comment by aviaryan** [comment]
Okay, I have closed #22.
btw, which commits should I squash ? I am not sure, for me all commits are relatively distinct.

**Comment by sudheesh001** [comment]
rebased and merged.

**Pull request merged**
