### PR TITLE
Speaker Image

### PR DESCRIPTION
**Pull request by venkatabn**
Venkata B Nagothi - Speaker Image

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
Hey @venkatabn , Are your details there in `index.html` ?

**Comment by venkatabn** [comment]
Hi,

My details are not there in index.html - I am not sure if I need to enter
it ? I want to add my credentials as well, if you can help me do that, it
would be great.

Thanks,
Venkata B N

**Comment by mariobehling** [comment]
Thank you! Added it.

@jig08 Venkata is part of the PGDay. Cheers!

**Comment by jigyasa-grover** [comment]
Oh. Didn't know that @mariobehling :)

**Comment by venkatabn** [comment]
Hi,

Thanks for adding it. Yes, I am one of the speakers for pgDay Asia.

So, does that mean, my picture and credentials will be added to "
http://2016.fossasia.org/" website ? Please confirm.

Because, i have not shared my credentials yet. Please let me know the way
to do it.

Regards,
Venkata B N

**Pull request merged**
