### PR TITLE
Added hover property for social icons in the side menu

### PR DESCRIPTION
**Pull request by harsh-jindal**
Solved #164

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@akshatnitd @isuruAb Made the same changes in css/custom.css

**Comment by anshumanv** [comment]
Please provide a test link.

**Comment by harsh-jindal** [comment]
@anshumanv https://harsh-jindal.github.io/2016.fossasia.change/ this is the test link

**Review by anshumanv — APPROVED** [review]
LGTM

**Comment by anshumanv** [comment]
Make sure you reference the issue you're solving, i.e
Fixes #164 (in this case). :smile:

**Comment by harsh-jindal** [comment]
@anshumanv It does.

**Review by akshatnitd — APPROVED** [review]
Good work :)

**Pull request merged**
