### PR TITLE
loader Screen for schedule page.

### PR DESCRIPTION
**Pull request by SilentFlame**
@joerx I guess this time it's conflict free.
#26 resolved.

please provide your feedback on the work.
sorry for being too much confusing and closing last PR #59. @jig08

### CODE REVIEW

**Comment by SilentFlame** [comment]
preview of the above is present at [http://silentflame.github.io/2016.fossasia.org/schedule/](url)

**Comment by SilentFlame** [comment]
preview of the work can be seen at `http://silentflame.github.io/2016.fossasia.org/schedule/index.html`

**Comment by jigyasa-grover** [comment]
@joerx Seems fine to me. I am merging this.
@SilentFlame :v:

**Comment by SilentFlame** [comment]
Thanks @jig08 :smile: 

I think Issue #26 can be closed now.

**Comment by joerx** [comment]
Please don't randomly wire in your code without any regards for existing design. There is a clear separation of responsibilities here - SessionStore is not doing any UI manipulation, but it emitting events for controller code to listen to. Your code is breaking this pattern. Moreover, I gave a clear hint on how to do this properly on #59 - I'm sorry, but will have to revert your commit.

**Pull request merged**
