### PR TITLE
Profile links of speakers

### LINKED ISSUE #119: Missing profile links of speakers
No profile links for some speakers

### PR DESCRIPTION
**Pull request by Iulia2100**
fixes #119

### CODE REVIEW

**Review by the-codingninja — APPROVED** [review]

**Review by jigyasa-grover — APPROVED** [review]

**Review by abhinavk96 — CHANGES_REQUESTED** [review]
Great work ! Please change the commit message to something more suitable. Along the lines of `add missing speaker profile links` instead of `update index.html`

**Review by harshit98 — APPROVED** [review]

**Comment by harshit98** [comment]
@Iulia2100 Squash your commits. And for change commit message, you use `git commit --amend`

**Review by isuruAb — APPROVED** [review]
👍

**Comment by isuruAb** [comment]
thank you 👍

**Pull request merged**
