### PR TITLE
Added 8 missing speaker's profile list...

### PR DESCRIPTION
**Pull request by yashk0thari**
#138 I've solved this issue...

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/BetaKing2016.fossasia.org/ --> preview link

**Comment by yashk0thari** [comment]
If there are no conflicts, can we please merge

**Comment by yashk0thari** [comment]
??

**Review by akshatnitd — APPROVED** [review]
Looks good! But why did you delete the entire PR template while making a PR?

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
